package com.SWEN342.ChatApplicationBackend.User;

import org.springframework.data.repository.CrudRepository;

/**
 * Repository of autogenerated functions for modifying messages
 */
public interface UserRepository extends CrudRepository<User, Long> {

}