package com.SWEN342.ChatApplicationBackend.User;

import jakarta.persistence.*;

/**
 * Representation of a user in the application
 */
@Entity
public class User {
  /**
   * Autogenerated id of the user
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The first name of the user
   */
  @Column(name = "first_name", nullable = false)
  private String firstName;

  /**
   * The last name of the user
   */
  @Column(name = "last_name", nullable = false)
  private String lastName;

  /**
   * The username to display for the user
   */
  @Column(name = "user_name", nullable = false)
  private String userName;

  /**
   * The id of the socket that the client will connect on
   */
  @Column(name = "socket_id")
  private String socketId;

  public User(String firstName, String lastName, String username, String socketId) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.userName = username;
    this.socketId = socketId;
  }

  public String getSocketId() {
    return socketId;
  }

  public void setSocketId(String socketId) {
    this.socketId = socketId;
  }

  public String getUsername() {
    return userName;
  }

  public String getLastName() {
    return lastName;
  }

  public String getFirstName() {
    return firstName;
  }

  protected User() {

  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getId() {
    return id;
  }
}
