package com.SWEN342.ChatApplicationBackend.Message;

import org.springframework.data.repository.CrudRepository;

import java.util.List;

/**
 * Repository of autogenerated functions for modifying messages
 */
public interface MessageRepository extends CrudRepository<Message, Long> {
  /**
   * Get the list of {@link Message}s that belong in a specific {@linkplain com.SWEN342.ChatApplicationBackend.Conversation.Conversation Conversation}
   *
   * @param conversationId The id of the related conversation
   * @return The messages that are in the conversation
   */
  List<Message> findByConversationId(long conversationId);
}
