package com.SWEN342.ChatApplicationBackend.Message;

import com.SWEN342.ChatApplicationBackend.Conversation.Conversation;
import com.SWEN342.ChatApplicationBackend.User.User;
import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Representation of a message in the application
 */
@Entity
public class Message {
  /**
   * Autogenerated id of the message
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private Long id;

  /**
   * The {@link Conversation} that the message belongs to
   */
  @ManyToOne(optional = false)
  @JoinColumn(name = "conversation_id", nullable = false)
  private Conversation conversation;

  /**
   * The {@link User} that sent the message
   */
  @ManyToOne(optional = false)
  @JoinColumn(name = "sender_id", nullable = false, unique = true)
  private User sender;

  /**
   * The timestamp of when the message was added to the database
   */
  @Column(name = "sent_at", nullable = false)
  private LocalDateTime sentAt;

  /**
   * The message that was sent
   */
  @Column(name = "message", nullable = false)
  private String message;

  public Message(Conversation conversation, User sender, LocalDateTime sentAt, String message) {
    this.conversation = conversation;
    this.sender = sender;
    this.sentAt = sentAt;
    this.message = message;
  }

  public Message() {

  }

  public String getMessage() {
    return message;
  }


  public Long getId() {
    return id;
  }

  public User getSender() {
    return sender;
  }

  public LocalDateTime getSentAt() {
    return sentAt;
  }
}
