package com.SWEN342.ChatApplicationBackend.UserConversation;

import org.springframework.data.repository.CrudRepository;

/**
 * Repository of autogenerated functions for modifying user-conversations
 */
public interface UserConversationRepository extends CrudRepository<UserConversation, Long> {
}
