package com.SWEN342.ChatApplicationBackend.Conversation;

import org.springframework.data.repository.CrudRepository;

/**
 * Repository of autogenerated functions for modifying Conversations
 */
public interface ConversationRepository extends CrudRepository<Conversation, Long> {
}
