package com.SWEN342.ChatApplicationBackend.Conversation;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

/**
 * Representation of a conversation in the application
 */
@Entity
public class Conversation {
  /**
   * Autogenerated id for the conversation
   */
  @Id
  @GeneratedValue
  private Long id;

  /**
   * The name for the conversation
   */
  private String name;

  protected Conversation() {

  }
  public Conversation(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getId() {
    return id;
  }
}
